owner: TomsProject
repo: uptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  cname: tp-uptime.vercel.app
  # baseUrl: /your-repo-name
  logoUrl: https://assets.projectoms.com/image/Icon/big/icon-1024.webp
  name: Toms Project Uptime
  introTitle: "Toms Project Uptime is a new uptime monitor and status page, powered entirely by GitHub."
  introMessage: Toms Project Uptime Monitored from GitHub
  navbar:
    - title: Home
      href: https://projectoms.com
    - title: Status
      href: https://status.projectoms.com/
    - title: GitHub
      href: https://github.com/ytmo
      
