owner: TomsProject
repo: uptime

sites:
  - name: TP Main
    url: https://www.projectoms.com/pc/
    method: HEAD
  - name: TP Blog
    url: https://blog.projectoms.com/
    method: HEAD
  - name: TP.JE
    url: https://tp.je/
  - name: VTP.XYZ
    url: https://vtp.xyz/
  - name: TP API 1
    url: https://api.projectoms.com/
  - name: TP API 2
    url: https://api1.projectoms.com/
  - name: TP Assets
    url: https://assets.projectoms.com/
  - name: TP Avatar
    url: https://avatar.vtp.xyz/
  - name: 创客编程
    url: https://www.ckbctc.com/
  - name: TP Test
    url: https://test.projectoms.com/
  - name: TPCloud
    url: https://cloud.tp.je/
  - name: TP Short Link
    url: https://s.tp.je/
  - name: TP Web Disk
    url: https://pan.projectoms.com/
  - name: GitHub
    url: https://github.com/
  - name: Google
    url: https://www.google.com/
  - name: Facebook
    url: https://www.facebook.com/
  - name: Baidu
    url: https://www.baidu.com/
  - name: Tencent
    url: https://www.qq.com/
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  cname: tp-uptime.vercel.app
  # baseUrl: /your-repo-name
  logoUrl: https://assets.projectoms.com/image/Icon/big/icon-1024.webp
  name: Toms Project Uptime
  introTitle: "Toms Project Uptime is a new uptime monitor and status page, powered entirely by GitHub."
  introMessage: Toms Project Uptime Monitored from GitHub
  navbar:
    - title: Home
      href: https://projectoms.com
    - title: Status
      href: https://status.projectoms.com/
    - title: GitHub
      href: https://github.com/ytmo
     
 i18n:
  activeIncidents: 当前故障
  allSystemsOperational: 所有系统均可用
  incidentReport: "故障 #$NUMBER 报告 →"
  activeIncidentSummary: 开始于 $DATE 伴随 $POSTS 个公告
  incidentTitle: 故障 $NUMBER 详情
  incidentDetails: 故障详情
  incidentFixed: 已修复
  incidentOngoing: 进行中
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentViewOnGitHub: View on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: 实时状态
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: 响应时间 (ms)
  up: 正常
  down: 无法访问
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled


